tech: try to remove useless files during release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,21 +36,56 @@ jobs:
         run: pnpm install --frozen-lockfile
 
       - name: Build project
-        run: pnpm build
+        run: |
+          pnpm build
+          git add -f dist
 
-      - name: Create commit
+      - name: Set version
+        run: |
+          echo "Setting version to ${{ github.event.inputs.version }}"
+          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
+          git add package.json
+
+      - name: Clean files for release
+        run: |
+          set -e
+
+            FILES=$(node -p "require('./package.json').files?.join(' ') ?? ''")
+            echo "Keeping: $FILES"
+            # Add mandatory files manually
+            KEEP="package.json README.md LICENSE .git $FILES"
+            # Create rsync includes
+            INCLUDE=$(for file in $KEEP; do echo "--include=$file"; done)
+            echo "Included patterns:"
+            echo "$INCLUDE"
+
+            mkdir safe
+            for file in $KEEP; do
+              if [ -e "$file" ]; then
+                echo "✅ Keeping $file"
+                mkdir -p "safe/$(dirname "$file")"
+                cp -r "$file" "safe/$file"
+              else
+                echo "⚠️  File $file not found, skipping"
+              fi
+            done
+
+            # Clean current directory
+            find . -mindepth 1 -maxdepth 1 ! -name safe -exec rm -rf {} +
+
+            # Move kept files back
+            shopt -s dotglob nullglob
+            mv safe/* ./
+            rmdir safe || true
+
+            git add .
+
+      - name: Create commit & tag
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          echo "Setting version to ${{ github.event.inputs.version }}"
-          npm version ${{ github.event.inputs.version }} --no-git-tag-version
-          git add package.json
-          echo "Force add dist directory"
-          git add -f dist
-          git commit -m "Include dist directory for release" || echo "No changes to commit"
-          echo "Create tag"
+          git commit -m "Commit release files" || echo "No changes to commit"
           git tag ${{ github.event.inputs.version }}
-          echo "Push"
           git push origin ${{ github.event.inputs.version }}
           git reset --soft HEAD~1  # Undo commit but keep changes staged
 
